# Server Details
server:
  port: ${PORT:8081}

# Eureka Details
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/

# Application Details
spring:
  application:
    name: inventory-service
  # DataBase Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: admin
  # JPA Hibernate Config
  jpa:
    hibernate:
      ddl-auto: create-drop

# Management Tools Details
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus


  
